spring.application.name=digital_interrogation
server.port=5555
spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# C:\Program Files\Minio
# minio.exe server C:\minio-data --console-address ":9001"
minio.url= ${MINIO_URL}
minio.access.key= ${MINIO_ACCESS_KEY}
minio.secret.key= ${MINIO_SECRET_KEY}
minio.bucket.name=${MINIO_BUCKET_NAME}

# docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:management
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

audio.model.url=${AUDIO_MODEL_URL}
audio.model.port=${AUDIO_MODEL_PORT}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-part-count=-1


spring.mvc.async.request-timeout=600000