spring.application.name=digital_interrogation
server.port=${PORT}
spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# C:\Program Files\Minio
# minio.exe server C:\minio-data --console-address ":9001"
minio.url= ${MINIO_URL}
minio.access.key= ${MINIO_ACCESS_KEY}
minio.secret.key= ${MINIO_SECRET_KEY}
minio.bucket.name=${MINIO_BUCKET_NAME}

# docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:management
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.inter.queue=${RABBITMQ_INTER_QUEUE}
spring.rabbitmq.inter.exchange=${RABBITMQ_INTER_EXCHANGE}
spring.rabbitmq.inter.routing-key=${RABBITMQ_INTER_ROUTING_KEY}

spring.rabbitmq.inter.result.exchange=${RABBITMQ_INTER_RESULT_EXCHANGE}
spring.rabbitmq.inter.result.pending.routing-key=${RABBITMQ_INTER_RESULT_PENDING_ROUTING_KEY}
spring.rabbitmq.inter.result.processing.routing-key=${RABBITMQ_INTER_RESULT_PROCESSING_ROUTING_KEY}
spring.rabbitmq.inter.result.success.routing-key=${RABBITMQ_INTER_RESULT_SUCCESS_ROUTING_KEY}
spring.rabbitmq.inter.result.failure.routing-key=${RABBITMQ_INTER_RESULT_FAILURE_ROUTING_KEY}

spring.rabbitmq.dlq.queue=${RABBITMQ_DLQ_QUEUE}
spring.rabbitmq.dlq.exchange=${RABBITMQ_DLQ_EXCHANGE}
spring.rabbitmq.dlq.routing-key=${RABBITMQ_DLQ_ROUTING_KEY}


audio.model.url=${AUDIO_MODEL_URL}
audio.model.port=${AUDIO_MODEL_PORT}
audio.kaz.model.url=${AUDIO_KAZ_MODEL_URL}
audio.kaz.model.port=${AUDIO_KAZ_MODEL_PORT}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-part-count=-1


spring.mvc.async.request-timeout=600000